namespace Models
{
	public class BankBalanceSheet
	{
		public bool Calculated { get; set; }
		public string CompanyId { get; set; }
		public int FYear { get; set; }
		public string IndustryTemplate { get; set; }
		public StatementType Statement { get; set; }
		public long? CashCashEquivalents_1 { get; set; }
		public long? Interbankassets_2 { get; set; }
		public long? FedFundsSoldRepos_3 { get; set; }
		public long? OtherInterbankAssets_4 { get; set; }
		public long? ShortandLongTermInvestments_5 { get; set; }
		public long? TradingSecurities_6 { get; set; }
		public long? InvestmentSecuritiesAvailableforSale_7 { get; set; }
		public long? InvestmentSecuritiesHeldtoMaturity_8 { get; set; }
		public long? RealEstateInvestments_9 { get; set; }
		public long? OtherInvestments_10 { get; set; }
		public long? NetReceivables_11 { get; set; }
		public long? NetLoans_25 { get; set; }
		public long? ReserveforLoanLosses_24 { get; set; }
		public long? TotalLoans_23 { get; set; }
		public long? TotalCommercialLoans_12 { get; set; }
		public long? CommercialRealEstateLoans_13 { get; set; }
		public long? OtherCommercialLoans_14 { get; set; }
		public long? TotalConsumerLoans_15 { get; set; }
		public long? CreditCardLoans_16 { get; set; }
		public long? HomeEquityLoans_17 { get; set; }
		public long? FamilyResidentialLoans_18 { get; set; }
		public long? AutoLoans_19 { get; set; }
		public long? StudentLoans_20 { get; set; }
		public long? OtherConsumerLoans_21 { get; set; }
		public long? OtherLoans_22 { get; set; }
		public long? NetFixedAssets_26 { get; set; }
		public long? PropertyPlantEquipmentNet_27 { get; set; }
		public long? OperatingLeaseAssets_28 { get; set; }
		public long? Otherfixedassets_75 { get; set; }
		public long? IntangibleAssets_29 { get; set; }
		public long? Goodwill_30 { get; set; }
		public long? OtherIntangibleAssets_31 { get; set; }
		public long? InvestmentsinAssociates_32 { get; set; }
		public long? DeferredTaxAssets_33 { get; set; }
		public long? DerivativesHedging_34 { get; set; }
		public long? DiscontinuedOperations_35 { get; set; }
		public long? CustomerAcceptancesLiabilities_36 { get; set; }
		public long? OtherAssets_37 { get; set; }
		public long? TotalAssets_38 { get; set; }
		public long? TotalDeposits_44 { get; set; }
		public long? DemandDeposits_39 { get; set; }
		public long? InterestBearingDeposits_40 { get; set; }
		public long? SavingDeposits_41 { get; set; }
		public long? TimeDeposits_42 { get; set; }
		public long? OtherDeposits_43 { get; set; }
		public long? ShortTermBorrowingsRepos_45 { get; set; }
		public long? SecuritiesSoldUnderRepo_46 { get; set; }
		public long? TradingAccountLiabilities_47 { get; set; }
		public long? ShortTermCapitalLeases_48 { get; set; }
		public long? CurrentPortionofLongTermDebt_49 { get; set; }
		public long? ShortTermBorrowings_50 { get; set; }
		public long? PayablesBrokerDealers_51 { get; set; }
		public long? LongTermDebt_52 { get; set; }
		public long? LongTermCapitalLeases_53 { get; set; }
		public long? LongTermBorrowings_54 { get; set; }
		public long? PensionLiabilities_55 { get; set; }
		public long? Pensions_56 { get; set; }
		public long? OtherPostRetirementBenefits_57 { get; set; }
		public long? DeferredTaxLiabilities_58 { get; set; }
		public long? DerivativesHedging_59 { get; set; }
		public long? DiscontinuedOperations_60 { get; set; }
		public long? OtherLiabilities_61 { get; set; }
		public long? TotalLiabilities_62 { get; set; }
		public long? PreferredEquity_63 { get; set; }
		public long? ShareCapitalAdditionalPaidInCapital_64 { get; set; }
		public long? CommonStock_65 { get; set; }
		public long? AdditionalPaidinCapital_66 { get; set; }
		public long? OtherShareCapital_67 { get; set; }
		public long? TreasuryStock_68 { get; set; }
		public long? RetainedEarnings_69 { get; set; }
		public long? OtherEquity_70 { get; set; }
		public long? EquityBeforeMinorityInterest_71 { get; set; }
		public long? MinorityInterest_72 { get; set; }
		public long? TotalEquity_73 { get; set; }
		public long? TotalLiabilitiesEquity_74 { get; set; }
	}
}