namespace Models
{
	public class GeneralBalanceSheet
	{
		//general
		public bool Calculated { get; set; }

		public string CompanyId { get; set; }
		public int FYear { get; set; }
		public string IndustryTemplate { get; set; }
		public StatementType Statement { get; set; }
		public long? CashCashEquivalentsShortTermInvestments_1 { get; set; }
		public long? CashCashEquivalents_2 { get; set; }
		public long? ShortTermInvestments_3 { get; set; }
		public long? AccountsNotesReceivable_4 { get; set; }
		public long? AccountsReceivableNet_5 { get; set; }
		public long? NotesReceivableNet_6 { get; set; }
		public long? UnbilledRevenues_7 { get; set; }
		public long? Inventories_8 { get; set; }
		public long? RawMaterials_9 { get; set; }
		public long? WorkInProcess_10 { get; set; }
		public long? FinishedGoods_11 { get; set; }
		public long? OtherInventory_12 { get; set; }
		public long? OtherShortTermAssets_13 { get; set; }
		public long? PrepaidExpenses_14 { get; set; }
		public long? DerivativeHedgingAssets_15 { get; set; }
		public long? AssetsHeldforSale_16 { get; set; }
		public long? DeferredTaxAssets_17 { get; set; }
		public long? IncomeTaxesReceivable_18 { get; set; }
		public long? DiscontinuedOperations_19 { get; set; }
		public long? MiscellaneousShortTermAssets_20 { get; set; }
		public long? TotalCurrentAssets_21 { get; set; }
		public long? PropertyPlantEquipmentNet_22 { get; set; }
		public long? PropertyPlantEquipment_23 { get; set; }
		public long? AccumulatedDepreciation_24 { get; set; }
		public long? LongTermInvestmentsReceivables_25 { get; set; }
		public long? LongTermInvestments_26 { get; set; }
		public long? LongTermMarketableSecurities_27 { get; set; }
		public long? LongTermReceivables_28 { get; set; }
		public long? OtherLongTermAssets_29 { get; set; }
		public long? IntangibleAssets_30 { get; set; }
		public long? Goodwill_31 { get; set; }
		public long? OtherIntangibleAssets_32 { get; set; }
		public long? PrepaidExpense_33 { get; set; }
		public long? DeferredTaxAssets_34 { get; set; }
		public long? DerivativeHedgingAssets_35 { get; set; }
		public long? PrepaidPensionCosts_36 { get; set; }
		public long? DiscontinuedOperations_37 { get; set; }
		public long? InvestmentsinAffiliates_38 { get; set; }
		public long? MiscellaneousLongTermAssets_39 { get; set; }
		public long? TotalNoncurrentAssets_40 { get; set; }
		public long? TotalAssets_41 { get; set; }
		public long? PayablesAccruals_42 { get; set; }
		public long? AccountsPayable_43 { get; set; }
		public long? AccruedTaxes_44 { get; set; }
		public long? InterestDividendsPayable_45 { get; set; }
		public long? OtherPayablesAccruals_46 { get; set; }
		public long? ShortTermDebt_47 { get; set; }
		public long? ShortTermBorrowings_48 { get; set; }
		public long? ShortTermCapitalLeases_49 { get; set; }
		public long? CurrentPortionofLongTermDebt_50 { get; set; }
		public long? OtherShortTermLiabilities_51 { get; set; }
		public long? DeferredRevenue_52 { get; set; }
		public long? DerivativesHedging_53 { get; set; }
		public long? DeferredTaxLiabilities_54 { get; set; }
		public long? DiscontinuedOperations_55 { get; set; }
		public long? MiscellaneousShortTermLiabilities_56 { get; set; }
		public long? TotalCurrentLiabilities_57 { get; set; }
		public long? LongTermDebt_58 { get; set; }
		public long? LongTermBorrowings_59 { get; set; }
		public long? LongTermCapitalLeases_60 { get; set; }
		public long? OtherLongTermLiabilities_61 { get; set; }
		public long? AccruedLiabilities_62 { get; set; }
		public long? PensionLiabilities_63 { get; set; }
		public long? Pensions_64 { get; set; }
		public long? OtherPostRetirementBenefits_65 { get; set; }
		public long? DeferredCompensation_66 { get; set; }
		public long? DeferredRevenue_67 { get; set; }
		public long? DeferredTaxLiabilities_68 { get; set; }
		public long? DerivativesHedging_69 { get; set; }
		public long? DiscontinuedOperations_70 { get; set; }
		public long? MiscellaneousLongTermLiabilities_71 { get; set; }
		public long? TotalNoncurrentLiabilities_72 { get; set; }
		public long? TotalLiabilities_73 { get; set; }
		public long? PreferredEquity_74 { get; set; }
		public long? ShareCapitalAdditionalPaidInCapital_75 { get; set; }
		public long? CommonStock_76 { get; set; }
		public long? AdditionalPaidinCapital_77 { get; set; }
		public long? OtherShareCapital_78 { get; set; }
		public long? TreasuryStock_79 { get; set; }
		public long? RetainedEarnings_80 { get; set; }
		public long? OtherEquity_81 { get; set; }
		public long? EquityBeforeMinorityInterest_82 { get; set; }
		public long? MinorityInterest_83 { get; set; }
		public long? TotalEquity_84 { get; set; }
		public long? TotalLiabilitiesEquity_85 { get; set; }
	}
}